### PR TITLE
✨ Add links between Sessions 61 and 55, referencing the Airtel GitHub…

### PR DESCRIPTION
**Pull request by sreekaransrinath**
… Pages issue.

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
In the links referring to specific CatchUp sessions, can you please use links that point to the individual CatchUps pages?
i.e.,
- `https://catchup.ourtech.community/summary/62` ✅ 
- `https://catchup.ourtech.community/summary/062` ❌ 
- `https://catchup.ourtech.community/summary#62` ❌

**Comment by HarshKapadia2** [comment]
Any updates, @sreekaransrinath?

**Comment by HarshKapadia2** [comment]
@sreekaransrinath any update on this PR?

**Comment by HarshKapadia2** [comment]
@sreekaransrinath?

**Comment by HarshKapadia2** [comment]
@sreekaransrinath can you please look into this?

**Comment by KartikSoneji** [comment]
@sreekaransrinath Since it's been over 7 months, I've gone ahead and corrected the urls.
@HarshKapadia2 please review and merge.

**Pull request merged**
