### PR TITLE
redirect: `/cfp` to talks website

### PR DESCRIPTION
**Pull request by tusharnankani**
Remove cfp page, aand redirect to talks.

### CODE REVIEW

**Review by SirusCodes — APPROVED** [review]

**Comment by tusharnankani** [comment]
https://github.com/OurTechCommunity/catchup/actions/runs/3659614942/jobs/6185809991

Yes, I forgot to run prettier. What are we supposed to do now? @KartikSoneji @HarshKapadia2 

FYI: It is not mentioned in [CONTRIBUTING](https://github.com/OurTechCommunity/catchup/blob/main/CONTRIBUTING.md)

**Comment by KartikSoneji** [comment]
Run prettier, amend the commit then force push.

**Comment by tusharnankani** [comment]
I wish there was a better way to do it. 

Although, I'll just normal push for now and we can stash and merge.

**Comment by KartikSoneji** [comment]
*squash and merge

But what's the issue in force-pushing?

**Comment by tusharnankani** [comment]
No issue as such. Saves me time to run an extra command.

Plus, would there be any major difference?

**Comment by KartikSoneji** [comment]
> Plus, would there be any major difference?

Not really.

**Comment by tusharnankani** [comment]
Fixed. Let's go!

**Pull request merged**
