### PR TITLE
:bug: fix: mobile view of admin page (#11)

### LINKED ISSUE #11: bug: fix the mobile view of the admin page
Adding the [issue](https://github.com/OurTechCommunity/website/issues/6) here from [web-site](https://github.com/OurTechCommunity/website). 

- Add some margin for the mobile view of the [admin page](https://catchup.ourtech.community/admin).

### PR DESCRIPTION
**Pull request by tusharnankani**
Fixes #11 

Current behavior: 

https://user-images.githubusercontent.com/61280281/147118787-b355e0ef-4b8b-45a1-8204-8883a65180c0.mp4

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
I think the form's font size is the only property that needs to be changed.

Can you please fetch this PR locally @dheerajdlalwani and check on your mobile?
Also check how it looks by only changing the form's font size.
Let us know the result of both.

Whatever is the result, the [CSS clamp() function](https://blog.webdevsimplified.com/2020-11/css-clamp) will be used to handle the font @tusharnankani, so you'll have to change the form font size in the CSS (https://github.com/OurTechCommunity/catchup/blob/main/public/css/style.css#L123-L128) to use the `clamp()` function. (The normal `font-size` property version  is to be kept as a fallback, with a quantity between the extremes in the `clamp()` function.)

**Comment by tusharnankani** [comment]
Any updates? @dheerajdlalwani

**Comment by HarshKapadia2** [comment]
Any updates @dheerajdlalwani?

**Comment by dheerajdlalwani** [comment]
I haven't gotten to it. Sorry for the late reply. Will give updates by the next week.

**Comment by tusharnankani** [comment]
Let deploy my local branch and give me a heads up if all looks good? 

@dheerajdlalwani

**Comment by tusharnankani** [comment]
How can I deploy my local branch? @HarshKapadia2

**Comment by HarshKapadia2** [comment]
There are local deployment instructions in the [`CONTRIBUTING.md`](https://github.com/OurTechCommunity/catchup/blob/main/CONTRIBUTING.md) file, @tusharnankani. That should work like the hosted web app (other than the CatchUp joining part, which uses [Deta](https://deta.sh)).

Do you want to host the web app? If yes, why? I mean you can use [Deta](https://deta.sh) if you wish to, but I don't think it is required. If you want to test the web app on your mobile, you can do that using the localhost as well, using port forwarding or [nip.io](https://nip.io).

**Comment by tusharnankani** [comment]
Why do I want to? 
https://github.com/OurTechCommunity/catchup/pull/13#issuecomment-1013261872

Cool. Thanks!

**Comment by HarshKapadia2** [comment]
Yeah I realised that I completely misunderstood the context. My bad. Sorry.

You'll have to deploy on [Deta](https://deta.sh), I guess.

**Comment by tusharnankani** [comment]
Why Deta?

Can't I use the other method?

**Comment by HarshKapadia2** [comment]
How will you use port forwarding to let @dheerajdlalwani use it? He is not in your local network...

**Comment by tusharnankani** [comment]
Oh yeah. Damn this is embarrassing hahaha. Oof okay. 
Let Dheeraj take a quick look when he's free.

**Comment by HarshKapadia2** [comment]
No issues at all!

**Comment by tusharnankani** [comment]
Is this fixed? @HarshKapadia2 

Can you take a look? @dheerajdlalwani

**Review by dheerajdlalwani — CHANGES_REQUESTED** [review]
Looks alright to me. Here's how it looks on the mobile:

image

Also, this seems like a good idea:
https://github.com/OurTechCommunity/catchup/issues/11#issuecomment-999678950

Also, add type=url to the input field.

**Comment by dheerajdlalwani** [comment]
> Why Deta?
> 
> Can't I use the other method?

You can use [localtunnel](https://github.com/localtunnel/localtunnel) to temporarily share a web service on your local development machine without messing with DNS and firewall settings.

**Comment by HarshKapadia2** [comment]
@dheerajdlalwani and @tusharnankani any updates?
Please finalize changes and merge this.

**Comment by tusharnankani** [comment]
Conflict fixed.

**Comment by tusharnankani** [comment]
image

Should we squash and merge PRs like these as well?

**Comment by SirusCodes** [comment]
We only squash and merge catchup summaries as there are a lot of commits which might not be necessary to be in our commit history.

**Comment by KartikSoneji** [comment]
> We only squash and merge catchup summaries as there are a lot of commits which might not be necessary to be in our commit history.

Two of the three commits are merge commits, and for a simple change like this I would prefer having only one clean commit on the branch.
It doesn't matter as much right now, but unnecessary merge commits make the history much harder to follow.
@tusharnankani you can either rebase onto main and drop the merge commits or we can squash and merge.

**Comment by tusharnankani** [comment]
I think I prefer squashing these for the same reasons. 2 out of 3 are merge commits. 

Let's sqaush them.

**Comment by SirusCodes** [comment]
Go ahead @tusharnankani

**Pull request merged**
